name: Dask
description: Spin up an on-demand Dask cluster with CML Workers.
author: Cloudera Inc.
specification_version: 1.0
prototype_version: 1.0
date: "2021-10-29"
api_version: 1

runtimes:
  - editor: Workbench
    kernel: Python 3.7
    edition: Standard
    version: 2021.09